from __future__ import annotations

import sympy as sp

# Exact symbolic audit of the current-bending q-conjugate equation.
# No numerical spatial quadrature is used.

x, y = sp.symbols('x y', real=True)
b, ell, q, q0 = sp.symbols('b ell q q0', positive=True)
Dx, Dy, Dmu, D66, Km, P = sp.symbols(
    'Dx Dy Dmu D66 Km P', real=True
)

alpha = sp.pi / b
beta = sp.pi / ell
psi = sp.sin(alpha*x) * sp.sin(beta*y)

# Current gross common curvatures generated by Delta w_g = b q psi.
kx = b*q*alpha**2*psi
ky = b*q*beta**2*psi
kxy = -2*b*q*alpha*beta*sp.cos(alpha*x)*sp.cos(beta*y)

kx_q = sp.diff(kx, q)
ky_q = sp.diff(ky, q)
kxy_q = sp.diff(kxy, q)

# Frozen initial orthotropic elastic moment law.
Mx = Dx*kx + Dmu*ky
My = Dmu*kx + Dy*ky
Mxy = D66*kxy

# Full one-halfwave current-bending generalized force.
Bcur = sp.simplify(
    4/(b**2*ell)
    * sp.integrate(
        sp.integrate(Mx*kx_q + My*ky_q + Mxy*kxy_q, (x, 0, b)),
        (y, 0, ell),
    )
)

H = Dmu + 2*D66
Kb = Dx*alpha**4 + 2*H*alpha**2*beta**2 + Dy*beta**4

assert sp.simplify(Bcur - b*Kb*q) == 0

# Repaired global q equation.
Rq_CB = sp.expand(
    Bcur
    + Km*b**3*q*(q + q0)*(q + 2*q0)
    - P*beta**2*(q + q0)
)

P_from_Rq = sp.solve(sp.Eq(Rq_CB, 0), P)[0]
Pcr = b*Kb/beta**2
C = b**3*Km/beta**2
P_old = Pcr*q/(q + q0) + C*q*(q + 2*q0)

assert sp.simplify(P_from_Rq - P_old) == 0

# Equivalent modal-moment check.
Mhat_x = sp.simplify(4/(b*ell) * sp.integrate(sp.integrate(Mx*psi, (x,0,b)), (y,0,ell)))
Mhat_y = sp.simplify(4/(b*ell) * sp.integrate(sp.integrate(My*psi, (x,0,b)), (y,0,ell)))
Mhat_xy = sp.simplify(
    4/(b*ell)
    * sp.integrate(
        sp.integrate(Mxy*sp.cos(alpha*x)*sp.cos(beta*y), (x,0,b)),
        (y,0,ell),
    )
)
Bmodal = sp.simplify(alpha**2*Mhat_x + beta**2*Mhat_y - 2*alpha*beta*Mhat_xy)
assert sp.simplify(Bmodal - Bcur) == 0

print('CURRENT_BENDING_RQ_DERIVED = PASS')
print('ELASTIC_AIRY_REGRESSION = EXACT_PASS')
print('Pcr_REGRESSION = EXACT_PASS')
print('C_REGRESSION = EXACT_PASS')
print('Bcur - b*Kb*q =', sp.simplify(Bcur - b*Kb*q))
print('P_from_Rq - P_old =', sp.simplify(P_from_Rq - P_old))
print('Bmodal - Bcur =', sp.simplify(Bmodal - Bcur))
